version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Typecheck
          command: npm run typecheck
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm run test
      - run:
          name: Integration Test
          command: AWS_REGION=us-east-1 npm run test:integration:ci
  publish:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Typecheck
          command: npm run typecheck
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm run test
      - run:
          name: Build
          command: npm run build
      - run:
          name: Publish
          command: |
            npm set //registry.npmjs.org/:_authToken=$GENERATIVE_TS_NPM_TOKEN
            npm run publish

workflows:
  version: 2
  raise_pr:
    when:
      and:
        - not:
            equal: [main, << pipeline.git.branch >>]
        - not:
            matches:
              pattern: '^release\/.*$'
              value: << pipeline.git.branch >>
    jobs:
      - test:
          context:
            - econify-aws
            - generative-ts-hf-token
  push_release_branch:
    jobs:
      - publish:
          context:
            - generative-ts-npm-token
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^release\/(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|(?:[0-9A-Za-z-]*[A-Za-z-][0-9A-Za-z-]*))(?:\.(?:0|[1-9]\d*|(?:[0-9A-Za-z-]*[A-Za-z-][0-9A-Za-z-]*)))*))?(?:\+([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?$/
